# Generated by Django 4.1.5 on 2023-01-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeAnAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Accepted'), ('2', 'Closed')], default=0, max_length=20)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
