# Generated by Django 4.1.5 on 2023-01-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_blogmodel_newslettersmodel_pricesmodel_servicemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioncentermodel',
            name='pricing',
        ),
        migrations.AddField(
            model_name='collectioncentermodel',
            name='pricing',
            field=models.ManyToManyField(to='account.pricesmodel'),
        ),
    ]
