# Generated by Django 4.1.5 on 2023-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_contaclformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaclformmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
