# Generated by Django 4.1.5 on 2023-01-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_contaclformmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioncentermodel',
            name='pricing',
        ),
        migrations.DeleteModel(
            name='PricesModel',
        ),
    ]
