# Generated by Django 4.1.5 on 2023-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_collectioncentermodel_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncentermodel',
            name='google_map_link',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
